### ISSUE TITLE
docker exec -ti 3cx /usr/sbin/3CXWizard --cleanup

### ISSUE THREAD

**Issue by 2Peti** [ekondayan/docker-3cx#1]
When I do docker exec -ti 3cx /usr/sbin/3CXWizard --cleanup
I get this error:
Failed to connect to bus: No such file or directory

Full command output:
Removed /etc/systemd/system/3CXQueueManager01.service.
Removed /etc/systemd/system/3CXCallFlow01.service.
Removed /etc/systemd/system/3CXSystemService01.service.
Removed /etc/systemd/system/3CXEventNotificationManager.service.
Removed /etc/systemd/system/3CXIVR01.service.
Removed /etc/systemd/system/multi-user.target.wants/3CXQueueManager01.service.
Removed /etc/systemd/system/multi-user.target.wants/3CXCallFlow01.service.Removed /etc/systemd/system/multi-user.target.wants/3CXSystemService01.service.
Removed /etc/systemd/system/multi-user.target.wants/3CXEventNotificationManager.service.
Removed /etc/systemd/system/multi-user.target.wants/3CXIVR01.service.
Removed /etc/systemd/system/multi-user.target.wants/3CXPhoneSystemMC01.service.
Removed /etc/systemd/system/multi-user.target.wants/3CXPhoneSystem01.service.
Removed /etc/systemd/system/multi-user.target.wants/3CXHotelModule01.service.
Removed /etc/systemd/system/multi-user.target.wants/3CXTunnel01.service.
Removed /etc/systemd/system/multi-user.target.wants/3CXMediaServer.service.
Removed /etc/systemd/system/multi-user.target.wants/3CXCfgServ01.service.
Removed /etc/systemd/system/multi-user.target.wants/3CXAudioProvider01.service.
Removed /etc/systemd/system/3CXPhoneSystemMC01.service.
Removed /etc/systemd/system/3CXPhoneSystem01.service.
Removed /etc/systemd/system/3CXHotelModule01.service.
Removed /etc/systemd/system/3CXTunnel01.service.
Removed /etc/systemd/system/3CXMediaServer.service.
Removed /etc/systemd/system/3CXCfgServ01.service.
Removed /etc/systemd/system/3CXAudioProvider01.service.
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory

**Comment by ekondayan** [comment]
Hi,
I can not reproduce it. It looks like a permissions problem.

How did you start the container?
What operating system you are using as a host?
Which is the version of the docker?
Are Apparmor or SELinux enabled on the host?

Regards,

**Comment by GenesisAdam** [comment]
I got the same error message on Synology NAS. 
Synology NAS uses Apparmor so I included the command:
--security-opt apparmor=unconfined
as suggested by you when running the container but it made no difference.
Docker version is:
Version:           18.09.8
 API version:       1.39
 Go version:        go1.11
 Git commit:        bfed4f5
 Built:             Thu Mar 18 02:58:09 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Please any help will be greatly appreciated.

**Comment by robvdl** [comment]
Running into the same issue, the setup command seems to deregister all the services, I don't get it:

I described the same problem here, with a full log:

https://github.com/mop1987/3cx-Docker/issues/3

**Comment by ekondayan** [comment]
Please follow this issue: https://github.com/ekondayan/docker-3cx/issues/9
