### ISSUE TITLE
pulling image into unraid - can't download image.

### ISSUE THREAD

**Issue by 436974697a656e466f7572** [ekondayan/docker-3cx#10]
Hey,

Wanted to test out 3cx inside of a docker instead of the VM I currently use. It seems your image is popular but when I'm trying to add the container via unraid I get the the following errors.

`Pulling image: farfui/3cx:latest

TOTAL DATA PULLED: 0 B

Command:
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='3cx' --net='bridge' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" 'farfui/3cx'
Unable to find image 'farfui/3cx:latest' locally
docker: Error response from daemon: manifest for farfui/3cx:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.

The command failed.`

Any ideas on this?

**Comment by loqster** [comment]
I don't think the registry has a latest tag for the images. 
Need to try one of the version 
In example farfui/3cx:16.0.8.9

**Comment by ekondayan** [comment]
@436974697a656e466f7572 The registry does not have a latest tag as loqster noted.
Please try: `farfui/3cx:18.0.2.314`
