### ISSUE TITLE
httpS links in docker file

### ISSUE THREAD

**Issue by mrkazoodle** [ekondayan/docker-3cx#17]
Hi,

I can't help but notice the http links in the docker file: probably httpS it's available?

`...
 && wget -O- http://downloads.3cx.com/downloads/3cxpbx/public.key | apt-key add - \  
 && echo "deb http://downloads.3cx.com/downloads...`

Best regards

**Comment by ekondayan** [comment]
In the latest commit this line has been replaced with: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D34B9BFD90503A6B

Latest commit: 1b0d0601d2cefd61db239e2bb3cdaf15dd116a79

Thank you


P.S.: I shall update the README.md
