### ISSUE TITLE
Version Upgrade to v18

### ISSUE THREAD

**Issue by e-skulk** [ekondayan/docker-3cx#8]
Hi,

a newer version is available: [3cx blog v18](https://www.3cx.com/blog/releases/v18-final/).
Would you bump the version to v18?

Thanks

**Comment by ekondayan** [comment]
The 3CX  version is updated to 18.0.0.1880.
The Debian version switched from Scratch to Buster. According to the 3cx website it is compatible.
Images are uploaded to docker hub.
